import type { Metadata } from "next";
import { Inter } from "next/font/google";
import { Toaster } from "sonner";

import "../globals.css";
import { ThemeProviders } from "../theme-providers";

const InterSans = Inter({
  variable: "--font-inter-sans",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Ganat",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" suppressHydrationWarning>
      <body className={`${InterSans.variable} antialiased`}>
        <ThemeProviders>
          {children}
          <Toaster theme="system" richColors position="bottom-left" />
        </ThemeProviders>
      </body>
    </html>
  );
}
