import Header from "@/components/layout/Header";
import MentorsSidebar from "@/components/layout/MentorsSidebar";
import type { Metadata } from "next";

export const metadata: Metadata = {
  title: "Ganat",
  description: "Generated by create next app",
};

export default function MentorsLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {

  return (
    <main className="mx-auto box-border max-w-5xl px-12 max-md:px-4">
      <div className="flex gap-16">
        <MentorsSidebar/>
        {children}
      </div>
    </main>
  );
}
