import MentorsSidebar from "@/components/layout/MentorsSidebar";
import type { Metadata } from "next";

export const metadata: Metadata = {
  title: "Ganat",
  description: "Generated by create next app",
};

export default function MentorsLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <main className="mx-auto box-border max-w-4xl px-12 max-lg:px-8 max-md:px-3">
      <div className="flex gap-16 max-lg:gap-10 max-md:gap-2">
        <MentorsSidebar />
        {children}
      </div>
    </main>
  );
}
